version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 5002:80
    links:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
  php:
    build: config
    ports:
      - 1026:80
    volumes:
      - .:/var/www/html:rw